version: "3.7"

services:
  tutor:
    build: .
    container_name: tutor
    user: root  # optional: change to "tutor" after initial setup
    volumes:
      - tutor-data:/home/tutor/.local/share/tutor
      - tutor-env:/home/tutor/.local/share/tutor/env
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/tutor
    stdin_open: true
    tty: true

volumes:
  tutor-data:
  tutor-env:
